version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  integracao-tabela-fipe:
    image: integracao-tabela-fipe:1.0
    container_name: integracao-tabela-fipe
    ports:
      - 8080:8080
    links:
      - mongo