version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: integracaoFipeMongodb
    ports:
      - "27017:27017"
    networks: ['mynetwork']
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      -   mongodb
    networks: ['mynetwork']
networks: {mynetwork: {}}